export * from './Header'
export * from './Tabs'
export * from './ListaClientesFidelizados'
export * from './Atendimento'
export * from '../pages/CadastroCliente'
export * from './ModalCadastroContato'
export * from './ModalCadastroTelefone'
export * from './Contatos'
