export * from './Header'
export * from './Tabs'
export * from './ListaClientesFidelizados'
export * from './Atendimento'
export * from '../pages/CadastroCliente'
export * from './ModalContato'
export * from './ModalTelefone'
export * from './Contatos'
